spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 16
      connection-timeout: 10000
      idle-timeout: 60000
      minimum-idle: 1
  liquibase:
    change-log: classpath:liquibase/changelog/changelog.yml
